AWSTemplateFormatVersion: "2010-09-09"
Description: Jane Doe (uksb-1q2j8beb0)

Parameters:

  ProvisionedDynamoDBReadCapacityUnits:
    Description: The DynamoDB Capacity Units allocated for reading the indexes. When this property or ProvisionedDynamoDBWriteCapacityUnits are set to 0, the billing mode is set to on-demand.
    Type: Number
    Default: 0

  ProvisionedDynamoDBWriteCapacityUnits:
    Description: The DynamoDB Capacity Units allocated for reading the indexes. When this property or ProvisionedDynamoDBReadCapacityUnits are set to 0, the billing mode is set to on-demand.
    Type: Number
    Default: 0

  DynamoDBTablePrefix:
    Description: The prefix usesed to name the DynamoDB tables on creation
    Type: String
    Default: JaneDoe

Conditions:
  DynamoDBOnDemand: !Or [!Equals [ !Ref ProvisionedDynamoDBReadCapacityUnits, 0 ] , !Equals [ !Ref ProvisionedDynamoDBWriteCapacityUnits, 0 ]]

Resources:

  ConfigurationTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${DynamoDBTablePrefix}_Configuration
      AttributeDefinitions: 
        - 
          AttributeName: S3Uri
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: S3Uri
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  MatchesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${DynamoDBTablePrefix}_Matches
      AttributeDefinitions: 
        - 
          AttributeName: MatchId
          AttributeType: S
        - 
          AttributeName: S3Uri
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: MatchId
          KeyType: HASH
        -
          AttributeName: S3Uri
          KeyType: RANGE
      BillingMode: !If [ DynamoDBOnDemand, PAY_PER_REQUEST, PROVISIONED ]
      ProvisionedThroughput:
        !If
          - DynamoDBOnDemand
          - !Ref AWS::NoValue
          - 
            ReadCapacityUnits : !Ref ProvisionedDynamoDBReadCapacityUnits
            WriteCapacityUnits : !Ref ProvisionedDynamoDBWriteCapacityUnits
        
  ObjectsStateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${DynamoDBTablePrefix}_ObjectsState
      AttributeDefinitions:
        -
          AttributeName: S3Uri
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: S3Uri
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
        