AWSTemplateFormatVersion: "2010-09-09"
Description: Amazon S3 Find and Forget DDB Tables

Parameters:

  DynamoDBTablePrefix:
    Description: The prefix usesed to name the DynamoDB tables on creation
    Type: String
    Default: S3F2

Resources:

  DeletionQueueTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${DynamoDBTablePrefix}_DeletionQueue
      AttributeDefinitions: 
        - 
          AttributeName: MatchId
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: MatchId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  DataMapperTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${DynamoDBTablePrefix}_DataMappers
      AttributeDefinitions:
        -
          AttributeName: DataMapperId
          AttributeType: S
      KeySchema:
        -
          AttributeName: DataMapperId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  JobTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${DynamoDBTablePrefix}_Jobs
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      AttributeDefinitions:
        -
          AttributeName: Id
          AttributeType: S
        -
          AttributeName: Type
          AttributeType: S
        -
          AttributeName: GSIBucket
          AttributeType: S
        -
          AttributeName: CreatedAt
          AttributeType: N
      KeySchema:
        -
          AttributeName: Id
          KeyType: HASH
        -
          AttributeName: Type
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        -
          IndexName: Date-GSI
          KeySchema:
            -
              AttributeName: GSIBucket
              KeyType: HASH
            -
              AttributeName: CreatedAt
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

Outputs:
  DeletionQueueTable:
    Value: !Ref DeletionQueueTable
  DataMapperTable:
    Value: !Ref DataMapperTable
  JobTable:
    Value: !Ref JobTable
  JobTableDateGSI:
    Value: Date-GSI
  JobTableStreamArn:
    Value: !GetAtt JobTable.StreamArn
