AWSTemplateFormatVersion: "2010-09-09"
Description: Jane Doe DDB Tables

Parameters:

  DynamoDBTablePrefix:
    Description: The prefix usesed to name the DynamoDB tables on creation
    Type: String
    Default: JaneDoe

Resources:

  DeletionQueueTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${DynamoDBTablePrefix}_DeletionQueue
      AttributeDefinitions: 
        - 
          AttributeName: MatchId
          AttributeType: S
      KeySchema: 
        - 
          AttributeName: MatchId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  DeletionQueueTable:
    Value: !Ref DeletionQueueTable
