AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Amazon S3 Find and Forget Deletion Flow

Parameters:
  AuditLogGroup:
    Type: String
  DeletionTaskCPU:
    Type: String
  DeletionTaskMemory:
    Type: String
  LogRetentionInDays:
    Type: Number
    Default: 7
  MaxFileSize:
    Type: String
    Default: 9
  ResourcePrefix:
    Type: String
  VpcSecurityGroup:
    Type: String
  VpcSubnets:
    Type: String

Resources:

  ECSCluster:
    Type: AWS::ECS::Cluster

  ECRRepository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain

  ECSTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  DelObjQ:
    Type: AWS::SQS::Queue
    Properties:
      ContentBasedDeduplication: true
      FifoQueue: true
      ReceiveMessageWaitTimeSeconds: 0
      VisibilityTimeout: 43200

  DeleteTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      TaskRoleArn: !Ref DeleteTaskIAMRole
      ExecutionRoleArn: !GetAtt ECSTaskExecutionRole.Arn
      NetworkMode: awsvpc
      Memory: !Ref DeletionTaskMemory
      Cpu: !Ref DeletionTaskCPU
      RequiresCompatibilities:
        - FARGATE
      ContainerDefinitions:
        - Name: !Sub ${ResourcePrefix}_DeleteTask
          Essential: true
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${ECRRepository}:latest
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref DeleteTaskLogGroup
              awslogs-region: !Ref 'AWS::Region'
              awslogs-stream-prefix: !Ref 'AWS::StackName'
          Environment:
            - Name: DELETE_OBJECTS_QUEUE
              Value: !Ref DelObjQ
            - Name: DLQ
              Value: !Ref DLQ
            - Name: ECS_ENABLE_CONTAINER_METADATA
              Value: 'true'
            - Name: LogGroupName
              Value: !Ref AuditLogGroup
            - Name: MAX_FILE_SIZE_GB
              Value: !Ref MaxFileSize

  DeleteService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !GetAtt ECSCluster.Arn
      DesiredCount: 0
      LaunchType: FARGATE
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups: [!Ref VpcSecurityGroup]
          Subnets: !Split [",", !Ref VpcSubnets]
      TaskDefinition: !Ref DeleteTaskDefinition

  DeleteTaskIAMRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: SqsExecutionPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Action: 
            - sqs:ChangeMessageVisibiliy
            - sqs:ChangeMessageVisibilityBatch 
            - sqs:DeleteMessage 
            - sqs:DeleteMessageBatch 
            - sqs:GetQueueAttributes 
            - sqs:ReceiveMessage
            Effect: Allow 
            Resource: !Sub arn:${AWS::Partition}:sqs:${AWS::Region}:${AWS::AccountId}:${DelObjQ.QueueName}
          - Action:
            - logs:DescribeLogStreams
            - logs:CreateLogStream
            - logs:PutLogEvents
            Effect: Allow
            Resource: "arn:aws:logs:*:*:*"
          # TODO: Remove for publishing
          - Action:
              - s3:PutObject
              - s3:Get*
              - s3:HeadBucket
              - s3:List*
            Effect: Allow
            Resource: "*"

  DeleteTaskLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: !Ref LogRetentionInDays

  DLQ:
    Type: AWS::SQS::Queue

Outputs:
  DeleteObjectsQueueUrl:
    Value: !Ref DelObjQ
  DeleteServiceName:
    Value: !GetAtt DeleteService.Name
  DeleteTaskIAMRoleArn:
    Value: !GetAtt DeleteTaskIAMRole.Arn
  DLQUrl:
    Value: !Ref DLQ
  ECSCluster:
    Value: !Ref ECSCluster
  ECRRepository:
    Value: !Ref ECRRepository
