AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: S3 Find and Forget Layers

Resources:
  AWSSDKLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AWSSDK
      Description: Latest confirmed compatible AWS SDK
      ContentUri: ../backend/lambda_layers/aws_sdk/
      CompatibleRuntimes:
        - python3.7
  Decorators:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Decorators
      Description: Helpful function decorators
      ContentUri: ../backend/lambda_layers/decorators/
      CompatibleRuntimes:
        - python3.7
  BotoUtils:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: BotoUtils
      Description: Helpful boto3 utils
      ContentUri: ../backend/lambda_layers/boto_utils/
      CompatibleRuntimes:
        - python3.7

Outputs:
  AWSSDKLayer:
    Description: "AWS SDK Layer"
    Value: !Ref AWSSDKLayer
  Decorators:
    Description: "Decorators Layer"
    Value: !Ref Decorators
  BotoUtils:
    Description: "Boto Utils Layer"
    Value: !Ref BotoUtils
