AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Jane Doe Layers

Resources:
  AWSSDKLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: AWSSDK
      Description: Latest confirmed compatible AWS SDK
      ContentUri: ../lambdas/layers/aws_sdk/
      CompatibleRuntimes:
        - python3.7
  Decorators:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: Decorators
      Description: Helpful function decorators
      ContentUri: ../lambdas/layers/decorators/
      CompatibleRuntimes:
        - python3.7

Outputs:
  AWSSDKLayer:
    Description: "AWS SDK Layer"
    Value: !Ref AWSSDKLayer
  Decorators:
    Description: "Decorators Layer"
    Value: !Ref Decorators
