AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: S3 Find and Forget State Machine

Globals:
  Function:
    Runtime: python3.7
    Timeout: 180
    AutoPublishAlias: live
    Tracing: Active
    Layers: !Ref CommonLayers
    Environment:
      Variables:
        LogLevel: !Ref LogLevel

Parameters:
  CommonLayers:
    Type: CommaDelimitedList
    Description: Common layers supplied to all functions
  DeletionQueueTableName:
    Description: Table name for Deletion Queue Table
    Type: String
  DataMapperTableName:
    Description: Table name for Data Mapper Table
    Type: String
  QueueUrl:
    Type: String
  LogLevel:
    Type: String
    Default: INFO
    AllowedValues:
    - CRITICAL
    - FATAL
    - ERROR
    - WARNING
    - INFO
    - DEBUG
    - NOTSET
  StateMachinePrefix:
    Type: String

Resources:
  StatesExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
        - Effect: "Allow"
          Principal:
            Service:
            - !Sub states.${AWS::Region}.amazonaws.com
          Action: "sts:AssumeRole"
      Path: "/"
      Policies:
      - PolicyName: StatesExecutionPolicy
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
          - Effect: Allow
            Action:
            - "lambda:InvokeFunction"
            Resource: "*"
          - Effect: Allow
            Action:
            - "sqs:SendMessage"
            Resource: "*"
          - Effect: Allow
            Action:
            - "dynamodb:DeleteItem"
            Resource: !Sub "arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DeletionQueueTableName}"
          - Effect: Allow
            Action:
            - "ecs:RunTask"
            - "ecs:StopTask"
            - "ecs:DescribeTasks"
            Resource: "*"
          - Effect: Allow
            Action:
            - "events:PutTargets"
            - "events:PutRule"
            - "events:DescribeRule"
            Resource: "*"
          - Effect: Allow
            Action:
            - "states:StartExecution"
            - "states:List*"
            - "states:Describe*"
            Resource: "*"

  StateMachineStub:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub ${StateMachinePrefix}-StateMachineStub
      DefinitionString: |-
        {
          "StartAt": "Pass",
          "States": {
            "Pass": {
              "Type": "Pass",
              "End": true
            }
          }
        }
      RoleArn: !GetAtt StatesExecutionRole.Arn

  AthenaStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub ${StateMachinePrefix}-AthenaStateMachine
      RoleArn: !GetAtt StatesExecutionRole.Arn
      DefinitionString: !Sub |-
        {
          "StartAt": "Generate Queries",
          "States": {
            "Generate Queries": {
              "Comment": "Generates a list of queries which need to be executed by Lambda",
              "Type": "Task",
              "Resource": "${GenerateQueries.Arn}",
              "ResultPath": "$.Queries",
              "Next": "Execute Queries"
            },
            "Execute Queries": {
              "Comment": "Executes the generated list of queries in parallel. Returns a list of lists",
              "Type": "Map",
              "End": true,
              "ItemsPath": "$.Queries",
              "ResultPath": "$",
              "MaxConcurrency": 10,
              "Iterator": {
                "StartAt": "Execute Query",
                "States": {
                  "Execute Query": {
                    "Comment": "Start an Athena query asynchronously",
                    "Type": "Task",
                    "Parameters": {
                      "QueryData.$": "$",
                      "Bucket": "${QueryResultBucket}",
                      "Prefix.$": "$$.Execution.Name"
                    },
                    "Resource": "${ExecuteQuery.Arn}",
                    "ResultPath": "$.QueryId",
                    "Next": "Get Query Status"
                  },
                  "Wait for Query": {
                    "Comment": "Waits before checking again whether Athena is done",
                    "Type": "Wait",
                    "Seconds": 30,
                    "Next": "Get Query Status"
                  },
                  "Get Query Status": {
                    "Comment": "Gets the status of the given Athena query",
                    "Type": "Task",
                    "Resource": "${CheckQueryStatus.Arn}",
                    "InputPath": "$.QueryId",
                    "ResultPath": "$.QueryStatus",
                    "Next": "Query Complete?"
                  },
                  "Query Complete?": {
                    "Comment": "Check if the Athena query is still running",
                    "Type": "Choice",
                    "Choices": [
                    {
                      "Variable": "$.QueryStatus.State",
                      "StringEquals": "SUCCEEDED",
                      "Next": "Query Succeeded"
                    },
                    {
                      "Or": [
                        {
                          "Variable": "$.QueryStatus.State",
                          "StringEquals": "FAILED"
                        },
                        {
                          "Variable": "$.QueryStatus.State",
                          "StringEquals": "CANCELLED"
                        }
                      ],
                      "Next": "Query Failed"
                    }
                    ],
                    "Default": "Wait for Query"
                  },
                  "Query Succeeded": {
                    "Comment": "The query was successful",
                    "Type": "Pass",
                    "Next": "Get Query Results"
                  },
                  "Get Query Results": {
                    "Comment": "Obtain the query results from S3, formatting as a JSON object",
                    "Type": "Task",
                    "Resource": "${GetQueryResults.Arn}",
                    "InputPath": "$.QueryId",
                    "ResultPath": "$.Paths",
                    "End": true
                  },
                  "Query Failed": {
                    "Comment": "The query was unsuccessful",
                    "Type": "Fail"
                  }
                }
              }
            }
          }
        }

  # Not exposed yet
  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub ${StateMachinePrefix}-StateMachine
      DefinitionString: !Sub |-
        {
          "Comment": "State machine for processing the S3 Find and Forget deletion queue.",
          "StartAt": "Check is Oldest Execution",
          "States": {
            "Check is Oldest Execution": {
              "Comment": "Queries the Step Functions API to check if the current executions is the oldest",
              "Type": "Task",
              "Resource": "${OldestExecutionCheck.Arn}",
              "Parameters": {
                "ExecutionId.$": "$$.Execution.Id"
              },
              "ResultPath": "$.IsOldestExecution",
              "Next": "Should Start?"
            },
            "Wait": {
              "Comment": "Waits before checking again whether this is the current execution",
              "Type": "Wait",
              "Seconds": 120,
              "Next": "Check is Oldest Execution"
            },
            "Should Start?": {
              "Comment": "Check if this execution is the oldest running execution and proceed if so.",
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.IsOldestExecution",
                  "BooleanEquals": true,
                  "Next": "Query Deletion Queue"
                },
                {
                  "Variable": "$.IsOldestExecution",
                  "BooleanEquals": false,
                  "Next": "Wait"
                }
              ],
              "Default": "CatchAllFallback"
            },
            "Query Deletion Queue": {
              "Comment": "Scan the deletion queue table to obtain all users to be deleted ",
              "Type": "Task",
              "Resource": "${ScanTable.Arn}",
              "Parameters": {
                "TableName": "${DeletionQueueTableName}"
              },
              "ResultPath": "$.DeletionQueue",
              "Next": "Users in Queue?"
            },
            "Users in Queue?": {
              "Comment": "If the deletion queue is empty, exit gracefully. Otherwise, proceed to processing the queue.",
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.DeletionQueue.Count",
                  "NumericGreaterThan": 0,
                  "Next": "Yes"
                },
                {
                  "Variable": "$.DeletionQueue.Count",
                  "NumericEquals": 0,
                  "Next": "No"
                }
              ],
              "Default": "No"
            },
            "No": {
              "Comment": "No work to be done.",
              "Type": "Succeed"
            },
            "Yes": {
              "Comment": "Continue.",
              "Type": "Pass",
              "Next": "Get Data Mappers"
            },
            "Get Data Mappers": {
              "Comment": "Gets the list of data mappers",
              "Type": "Task",
              "Parameters": {
                "TableName": "${DataMapperTableName}"
              },
              "Resource": "${ScanTable.Arn}",
              "ResultPath": "$.DataMappers",
              "Next": "Discover Files"
            },
            "Discover Files": {
              "Type": "Parallel",
              "Next": "Flatten Results",
              "ResultPath": "$.QueryResults",
              "Branches": [
                {
                  "StartAt": "Filter Glue Data Mappers",
                  "States": {
                    "Filter Glue Data Mappers": {
                      "Parameters": {
                        "DataMappers.$": "$.DataMappers.Items[?(@.DataSource=='glue')]",
                        "DeletionQueue.$": "$.DeletionQueue.Items"
                      },
                      "Comment": "Process Data Sources with type glue",
                      "Type": "Pass",
                      "Next": "Query Glue Catalogs"
                    },
                    "Query Glue Catalogs": {
                      "Type":"Task",
                      "Resource":"arn:aws:states:::states:startExecution.sync",
                      "Parameters":{
                        "Input.$": "$",
                        "StateMachineArn": "${AthenaStateMachine}",
                        "Name.$":"$$.Execution.Name"
                      },
                      "OutputPath": "$.Output",
                      "Next": "Parse State Machine Results"
                    },
                    "Parse State Machine Results": {
                      "Comment": "Parses the output from the state machine",
                      "Type": "Task",
                      "Resource": "${ParseStateMachineOutput.Arn}",
                      "End": true
                    }
                  }
                }
              ]
            },
            "Flatten Results": {
              "Comment": "Parses and flattens the result of all branches",
              "Type": "Pass",
              "InputPath": "$.QueryResults[*][*]",
              "ResultPath": "$.QueryResults",
              "Next": "Aggregate and Depduplicate Results"
            },
            "Aggregate and Depduplicate Results": {
              "Comment": "Aggregates the results and deduplicates",
              "Type": "Task",
              "InputPath": "$.QueryResults",
              "ResultPath": "$.QueryResults",
              "Resource": "${AggregateResults.Arn}",
              "Next": "Populate Queue"
            },
            "Populate Queue": {
              "Comment": "Creates queue items for every file",
              "Type": "Map",
              "Next": "Delete Query Results",
              "ItemsPath": "$.QueryResults",
              "ResultPath": "$.DeletionResults",
              "Iterator": {
                "StartAt": "Send Message",
                "States": {
                  "Send Message": {
                    "Type": "Task",
                    "Resource": "arn:aws:states:::sqs:sendMessage.waitForTaskToken",
                    "HeartbeatSeconds": 3600,
                    "Parameters": {
                      "QueueUrl": "${QueueUrl}",
                      "MessageGroupId.$": "$$.Execution.Id",
                      "MessageBody": {
                        "Input.$": "$",
                        "TaskToken.$": "$$.Task.Token"
                      }
                    },
                    "End": true
                  }
                }
              }
            },
            "Delete Query Results": {
              "Comment": "Deletes query results from the query result bucket",
              "Type": "Task",
              "Parameters": {
                "ExecutionName.$": "$$.Execution.Name"
              },
              "ResultPath": null,
              "Resource": "${DeleteQueryResults.Arn}",
              "Next": "Delete Queue Items"
            },
            "Delete Queue Items": {
              "Comment": "Deletes all items from the deletion queue",
              "Type": "Map",
              "End": true,
              "InputPath": "$.DeletionQueue.Items",
              "ItemsPath": "$",
              "ResultPath": null,
              "MaxConcurrency": 10,
              "Iterator": {
                "StartAt": "Delete Queue Item",
                "States": {
                  "Delete Queue Item": {
                    "Type": "Task",
                    "Resource": "arn:aws:states:::dynamodb:deleteItem",
                    "Parameters": {
                      "TableName": "${DeletionQueueTableName}",
                      "Key": {
                        "MatchId": {"S.$": "$.MatchId"}
                      }
                    },
                    "ResultPath": null,
                    "End": true
                  }
                }
              }
            },
            "CatchAllFallback": {
               "Type": "Pass",
               "Result": "This is a fallback from any error code",
               "End": true
            }
          }
        }
      RoleArn: !GetAtt StatesExecutionRole.Arn

  # Supporting Resources
  QueryResultBucket:
    Type: AWS::S3::Bucket

  # Tasks
  TaskStub:
    Type: AWS::Serverless::Function
    Properties:
      Handler: task_stub.handler
      CodeUri: ../lambdas/src/tasks/

  OldestExecutionCheck:
    Type: AWS::Serverless::Function
    Properties:
      Handler: oldest_execution.handler
      CodeUri: ../lambdas/src/tasks/
      Environment:
        Variables:
          StateMachineArn: !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${StateMachinePrefix}-StateMachine
      Policies:
      - Statement:
        - Action:
          - "states:ListExecutions"
          Effect: "Allow"
          Resource: !Sub arn:${AWS::Partition}:states:${AWS::Region}:${AWS::AccountId}:stateMachine:${StateMachinePrefix}*

  ScanTable:
    Type: AWS::Serverless::Function
    Properties:
      Handler: scan_table.handler
      CodeUri: ../lambdas/src/tasks/
      Policies:
      - DynamoDBReadPolicy:
          TableName: !Ref DeletionQueueTableName
      - DynamoDBReadPolicy:
          TableName: !Ref DataMapperTableName

  ParseStateMachineOutput:
    Type: AWS::Serverless::Function
    Properties:
      Handler: parse_output.handler
      CodeUri: ../lambdas/src/tasks/

  DeleteQueryResults:
    Type: AWS::Serverless::Function
    Properties:
      Handler: delete_query_results.handler
      CodeUri: ../lambdas/src/tasks/
      Environment:
        Variables:
          BucketName: !Ref QueryResultBucket
      Policies:
      - S3CrudPolicy:
          BucketName: !Ref QueryResultBucket

  ExecuteQuery:
    Type: AWS::Serverless::Function
    Properties:
      Handler: execute_query.handler
      CodeUri: ../lambdas/src/tasks/
      Policies:
      - S3CrudPolicy:
          BucketName: !Ref QueryResultBucket
      - Statement:
        - Action:
          - "athena:StartQueryExecution"
          - "glue:GetDatabase"
          - "glue:GetTable"
          - "glue:GetPartition*"
          Effect: "Allow"
          Resource: "*"

  CheckQueryStatus:
    Type: AWS::Serverless::Function
    Properties:
      Handler: check_query_status.handler
      CodeUri: ../lambdas/src/tasks/
      Policies:
      - Statement:
        - Action:
          - "athena:GetQueryExecution"
          Effect: "Allow"
          Resource: "*"

  GetQueryResults:
    Type: AWS::Serverless::Function
    Properties:
      Handler: get_query_results.handler
      CodeUri: ../lambdas/src/tasks/
      Policies:
      - S3ReadPolicy:
          BucketName: !Ref QueryResultBucket
      - Statement:
        - Action:
          - "athena:GetQueryResults"
          Effect: "Allow"
          Resource: "*"

  GenerateQueries:
    Type: AWS::Serverless::Function
    Properties:
      Handler: generate_queries.handler
      CodeUri: ../lambdas/src/tasks/
      Policies:
      - Statement:
        - Action:
          - "glue:GetDatabase"
          - "glue:GetTable*"
          - "glue:GetPartition*"
          Effect: "Allow"
          Resource: "*"

  AggregateResults:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aggregate_results.handler
      CodeUri: ../lambdas/src/tasks/

Outputs:
  StateMachineArn:
    Value: !Ref StateMachineStub
  StateMachineRoleArn:
    Value: !GetAtt StatesExecutionRole.Arn
  QueryResultBucket:
    Value: !Ref QueryResultBucket
