AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Jane Doe (uksb-1q2j8beb0)

Parameters:
  DynamoDBTablePrefix:
    Description: The prefix usesed to name the DynamoDB tables on creation
    Type: String
    Default: JaneDoe
  CognitoUserPoolName:
    Type: String
    Default: JaneDoePool
  CognitoUserPoolClientName:
    Type: String
    Default: JaneDoePoolClient

Resources:
  DDBStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./ddb.yaml
      Parameters:
        DynamoDBTablePrefix: !Ref DynamoDBTablePrefix
  APIStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./api.yaml
      Parameters: 
        DeletionQueueTable: !GetAtt DDBStack.Outputs.DeletionQueueTable
        CognitoUserPoolName: !Ref CognitoUserPoolName
        CognitoUserPoolClientName: !Ref CognitoUserPoolClientName

Outputs:
  DDBStack:
    Value: !Ref DDBStack
  APIStack:
    Value: !Ref APIStack
  DeletionQueueTable:
    Value: !GetAtt DDBStack.Outputs.DeletionQueueTable
