AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Jane Doe (uksb-1q2j8beb0)

Parameters:
  CognitoUserPoolName:
    Type: String
    Default: JaneDoePool
  CognitoUserPoolClientName:
    Type: String
    Default: JaneDoePoolClient
  DeletionTaskCPU:
    Description: The CPU to be allocated to the Deletion Fargate Task
    Type: String
    Default: '4096'
  DeletionTaskMemory:
    Description: The memory to be allocated to the Deletion Fargate Task
    Type: String
    Default: '30720'
  PublicSubnetIpBlocks:
    Description: Comma-delimited list of CIDR blocks for the public subnets
    Type: CommaDelimitedList
    Default: "10.0.12.0/22, 10.0.16.0/22, 10.0.20.0/22"
  ResourcePrefix:
    Description: The prefix used in DynamoDB table and state machine names
    Type: String
    Default: JaneDoe
  VpcIpBlock:
    Description: CIDR block for the VPC
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$

Resources:
  LayersStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./layers.yaml
  DDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ddb.yaml
      Parameters:
        DynamoDBTablePrefix: !Ref ResourcePrefix
  APIStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./api.yaml
      Parameters: 
        CognitoUserPoolClientName: !Ref CognitoUserPoolClientName
        CognitoUserPoolName: !Ref CognitoUserPoolName
        CommonLayers: !Join
          - ","
          - - !GetAtt LayersStack.Outputs.AWSSDKLayer
            - !GetAtt LayersStack.Outputs.Decorators
            - !GetAtt LayersStack.Outputs.BotoUtils
        DeletionQueueTableName: !GetAtt DDBStack.Outputs.DeletionQueueTable
        StateMachineArn: !GetAtt StateMachineStack.Outputs.StateMachineArn
  StateMachineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./state_machine.yaml
      Parameters:
        CommonLayers: !Join
          - ","
          - - !GetAtt LayersStack.Outputs.AWSSDKLayer
            - !GetAtt LayersStack.Outputs.Decorators
            - !GetAtt LayersStack.Outputs.BotoUtils
        DeletionQueueTableName: !GetAtt DDBStack.Outputs.DeletionQueueTable
        QueueUrl: !GetAtt DeletionFlowStack.Outputs.DeleteObjectsQueueUrl
        StateMachinePrefix: !Ref ResourcePrefix
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml
      Parameters:
        PublicSubnetIpBlocks: !Ref PublicSubnetIpBlocks
        VpcIpBlock: !Ref VpcIpBlock
  DeletionFlowStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./deletion_flow.yaml
      Parameters:
        DeletionTaskCPU: !Ref DeletionTaskCPU
        DeletionTaskMemory: !Ref DeletionTaskMemory
        ResourcePrefix: !Ref ResourcePrefix

Outputs:
  APIStack:
    Value: !Ref APIStack
  DDBStack:
    Value: !Ref DDBStack
  DeleteTaskIAMRoleArn:
    Value: !GetAtt StateMachineStack.Outputs.DeleteTaskIAMRoleArn
  DeletionQueueTable:
    Value: !GetAtt DDBStack.Outputs.DeletionQueueTable
