AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Jane Doe (uksb-1q2j8beb0)

Parameters:
  ResourcePrefix:
    Description: The prefix used in DynamoDB table and state machine names
    Type: String
    Default: JaneDoe
  CognitoUserPoolName:
    Type: String
    Default: JaneDoePool
  CognitoUserPoolClientName:
    Type: String
    Default: JaneDoePoolClient

Resources:
  LayersStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./layers.yaml
  DDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ddb.yaml
      Parameters:
        DynamoDBTablePrefix: !Ref ResourcePrefix
  APIStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./api.yaml
      Parameters: 
        DeletionQueueTableName: !GetAtt DDBStack.Outputs.DeletionQueueTable
        StateMachineArn: !GetAtt StateMachineStack.Outputs.StateMachineArn
        CognitoUserPoolName: !Ref CognitoUserPoolName
        CognitoUserPoolClientName: !Ref CognitoUserPoolClientName
        CommonLayers: !Join
          - ","
          - - !GetAtt LayersStack.Outputs.AWSSDKLayer
            - !GetAtt LayersStack.Outputs.Decorators
            - !GetAtt LayersStack.Outputs.BotoUtils
  StateMachineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./state_machine.yaml
      Parameters:
        DeletionQueueTableName: !GetAtt DDBStack.Outputs.DeletionQueueTable
        StateMachinePrefix: !Ref ResourcePrefix
        CommonLayers: !Join
          - ","
          - - !GetAtt LayersStack.Outputs.AWSSDKLayer
            - !GetAtt LayersStack.Outputs.Decorators
            - !GetAtt LayersStack.Outputs.BotoUtils

Outputs:
  DDBStack:
    Value: !Ref DDBStack
  APIStack:
    Value: !Ref APIStack
  DeletionQueueTable:
    Value: !GetAtt DDBStack.Outputs.DeletionQueueTable
