AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Amazon S3 Find and Forget (uksb-1q2j8beb0)

Parameters:
  AthenaConcurrencyLimit:
    Description: How many Athena queries should be scheduled concurrently
    Type: Number
    Default: 20
  AthenaWorkGroup:
    Description: WorkGroup to use for Athena queries
    Type: String
    Default: primary
  CognitoUserPoolName:
    Type: String
    Default: S3F2Pool
  CognitoUserPoolClientName:
    Type: String
    Default: S3F2PoolClient
  DeletionTaskCPU:
    Description: The CPU to be allocated to the Deletion Fargate Task
    Type: String
    Default: '4096'
  DeletionTasksMaxNumber:
    Description: The maximum number of tasks to allocate for the Deletion Fargate job
    Type: Number
    Default: 3
    MinValue: 1
  DeletionTaskMemory:
    Description: The memory to be allocated to the Deletion Fargate Task
    Type: String
    Default: '30720'
  LogRetentionInDays:
    Description: The number of days to retain raw job logs
    Type: Number
    Default: 7
  PrivateSubnetIpBlocks:
    Description: Comma-delimited list of CIDR blocks for the private subnets
    Type: String
    Default: "10.0.0.0/22, 10.0.4.0/22, 10.0.8.0/22"
  ResourcePrefix:
    Description: The prefix used in DynamoDB table and state machine names
    Type: String
    Default: S3F2
  VpcIpBlock:
    Description: CIDR block for the VPC
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$

Resources:
  LayersStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./layers.yaml
  DDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ddb.yaml
      Parameters:
        DynamoDBTablePrefix: !Ref ResourcePrefix
  APIStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./api.yaml
      Parameters: 
        CognitoUserPoolClientName: !Ref CognitoUserPoolClientName
        CognitoUserPoolName: !Ref CognitoUserPoolName
        CommonLayers: !Join
          - ","
          - - !GetAtt LayersStack.Outputs.AWSSDKLayer
            - !GetAtt LayersStack.Outputs.Decorators
            - !GetAtt LayersStack.Outputs.BotoUtils
        DeletionQueueTableName: !GetAtt DDBStack.Outputs.DeletionQueueTable
        DataMapperTableName: !GetAtt DDBStack.Outputs.DataMapperTable
        StateMachineArn: !GetAtt StateMachineStack.Outputs.StateMachineArn
  StateMachineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./state_machine.yaml
      Parameters:
        AthenaConcurrencyLimit: !Ref AthenaConcurrencyLimit
        AthenaWorkGroup: !Ref AthenaWorkGroup
        AuditLogGroup: !Ref AuditLogGroup
        CommonLayers: !Join
          - ","
          - - !GetAtt LayersStack.Outputs.AWSSDKLayer
            - !GetAtt LayersStack.Outputs.Decorators
            - !GetAtt LayersStack.Outputs.BotoUtils
        DeleteServiceName: !GetAtt DelStack.Outputs.DeleteServiceName
        DeletionQueueTableName: !GetAtt DDBStack.Outputs.DeletionQueueTable
        DeletionTasksMaxNumber: !Ref DeletionTasksMaxNumber
        DataMapperTableName: !GetAtt DDBStack.Outputs.DataMapperTable
        ECSCluster: !GetAtt DelStack.Outputs.ECSCluster
        DeleteQueueUrl: !GetAtt DelStack.Outputs.DeleteObjectsQueueUrl
        StateMachinePrefix: !Ref ResourcePrefix
  VpcStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yaml
      Parameters:
        PrivateSubnetIpBlocks: !Ref PrivateSubnetIpBlocks
        VpcIpBlock: !Ref VpcIpBlock
  DelStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./deletion_flow.yaml
      Parameters:
        AuditLogGroup: !Ref AuditLogGroup
        DeletionTaskCPU: !Ref DeletionTaskCPU
        DeletionTaskMemory: !Ref DeletionTaskMemory
        ResourcePrefix: !Ref ResourcePrefix
        VpcSecurityGroup: !GetAtt VpcStack.Outputs.SecurityGroup
        VpcSubnets: !GetAtt VpcStack.Outputs.Subnets

  AuditLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/s3f2/
      RetentionInDays: !Ref LogRetentionInDays

Outputs:
  APIStack:
    Value: !Ref APIStack
  ApiUrl:
    Value: !GetAtt APIStack.Outputs.ApiUrl
  AthenaStateMachineArn:
    Value: !GetAtt StateMachineStack.Outputs.AthenaStateMachineArn
  AthenaExecutionRoleArn:
    Value: !GetAtt StateMachineStack.Outputs.AthenaExecutionRoleArn
  AuditLogGroup:
    Value: !Ref AuditLogGroup
  CognitoUserPoolClientId:
    Value: !GetAtt APIStack.Outputs.CognitoUserPoolClientId
  CognitoUserPoolId:
    Value: !GetAtt APIStack.Outputs.CognitoUserPoolId
  DataMapperTable:
    Value: !GetAtt DDBStack.Outputs.DataMapperTable
  DDBStack:
    Value: !Ref DDBStack
  DeleteTaskIAMRoleArn:
    Value: !GetAtt DelStack.Outputs.DeleteTaskIAMRoleArn
  DeletionQueueTable:
    Value: !GetAtt DDBStack.Outputs.DeletionQueueTable
  ECRRepository:
    Value: !GetAtt DelStack.Outputs.ECRRepository
  DeletionQueueUrl:
    Value: !GetAtt DelStack.Outputs.DeleteObjectsQueueUrl
  QueryQueueUrl:
     Value: !GetAtt StateMachineStack.Outputs.QueryQueueUrl
  StateMachineArn:
    Value: !GetAtt StateMachineStack.Outputs.StateMachineArn
  StateMachineRoleArn:
    Value: !GetAtt StateMachineStack.Outputs.StateMachineRoleArn
