AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Jane Doe (uksb-1q2j8beb0)

Parameters:
  CognitoUserPoolName:
    Type: String
    Default: JaneDoePool
  CognitoUserPoolClientName:
    Type: String
    Default: JaneDoePoolClient
  DeletionTaskCPU:
    Description: The CPU to be allocated to the Deletion Fargate Task
    Type: String
    Default: '4096'
  DeletionTaskMemory:
    Description: The memory to be allocated to the Deletion Fargate Task
    Type: String
    Default: '30720'
  ResourcePrefix:
    Description: The prefix used in DynamoDB table and state machine names
    Type: String
    Default: JaneDoe

Resources:
  LayersStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./layers.yaml
  DDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ddb.yaml
      Parameters:
        DynamoDBTablePrefix: !Ref ResourcePrefix
  APIStack: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: ./api.yaml
      Parameters: 
        CognitoUserPoolClientName: !Ref CognitoUserPoolClientName
        CognitoUserPoolName: !Ref CognitoUserPoolName
        CommonLayers: !Join
          - ","
          - - !GetAtt LayersStack.Outputs.AWSSDKLayer
            - !GetAtt LayersStack.Outputs.Decorators
            - !GetAtt LayersStack.Outputs.BotoUtils
        DeletionQueueTableName: !GetAtt DDBStack.Outputs.DeletionQueueTable
        DataMapperTableName: !GetAtt DDBStack.Outputs.DataMapperTable
        StateMachineArn: !GetAtt StateMachineStack.Outputs.StateMachineArn
  StateMachineStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./state_machine.yaml
      Parameters:
        CommonLayers: !Join
          - ","
          - - !GetAtt LayersStack.Outputs.AWSSDKLayer
            - !GetAtt LayersStack.Outputs.Decorators
            - !GetAtt LayersStack.Outputs.BotoUtils
        DeletionQueueTableName: !GetAtt DDBStack.Outputs.DeletionQueueTable
        DeletionTaskCPU: !Ref DeletionTaskCPU
        DeletionTaskMemory: !Ref DeletionTaskMemory
        StateMachinePrefix: !Ref ResourcePrefix
        QueueUrl: !GetAtt DeletionFlowStack.Outputs.DeleteObjectsQueueUrl

  DeletionFlowStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./deletion_flow.yaml
      Parameters:
        DeletionTaskCPU: !Ref DeletionTaskCPU
        DeletionTaskMemory: !Ref DeletionTaskMemory
        ResourcePrefix: !Ref ResourcePrefix

Outputs:
  APIStack:
    Value: !Ref APIStack
  DDBStack:
    Value: !Ref DDBStack
  DeleteTaskIAMRoleArn:
    Value: !GetAtt StateMachineStack.Outputs.DeleteTaskIAMRoleArn
  DeletionQueueTable:
    Value: !GetAtt DDBStack.Outputs.DeletionQueueTable
  DataMapperTable:
    Value: !GetAtt DDBStack.Outputs.DataMapperTable
