AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Amazon S3 Find and Forget Web UI helper

Globals:
  Function:
    Runtime: python3.7
    Timeout: 900
    Layers: !Ref CommonLayers

Parameters:
  CommonLayers:
    Type: CommaDelimitedList
  LogLevel:
    Type: String
    Default: INFO
    AllowedValues:
    - CRITICAL
    - FATAL
    - ERROR
    - WARNING
    - INFO
    - DEBUG
    - NOTSET
  WebUIBucket:
    Type: String

Resources:

  CleanupWebUI:
    Type: Custom::Setup
    Properties:
      ServiceToken: !GetAtt RemoveAllObjects.Arn
      LogLevel: !Ref LogLevel
      Bucket: !Ref WebUIBucket

  RemoveAllObjects:
    Type: AWS::Serverless::Function
    Properties:
      Handler: cleanup_bucket.handler
      CodeUri: ../backend/lambdas/custom_resources/
      Description: Custom Lambda resource for the Amazon S3 Find and Forget Cloudformation Stack
      Policies:
        - Statement:
          - Effect: Allow
            Action: 
              - s3:DeleteObject
              - s3:ListBucket
            Resource:
              - !Sub arn:aws:s3:::${WebUIBucket}
              - !Sub arn:aws:s3:::${WebUIBucket}/*
          